name = "shafa-hono"
account_id = "287572e2291030d8c5e360fcc593a16b"
compatibility_date = "2023-01-01"

[durable_objects]
bindings = [
    {name = "ITEM", class_name = "Item"},
    {name = "OUTFIT", class_name = "Outfit"},
    {name = "USER", class_name = "User"}
]

[[migrations]]
tag = "v1"
new_classes = ["Item", "Outfit", "User"]