name = "shafa-hono"
account_id = "287572e2291030d8c5e360fcc593a16b"
compatibility_date = "2024-02-01"

d1_databases = [
    { binding = "DB", database_name = "dev-shafa-hono-db", database_id = "9a371c58-cb3e-4126-bf4d-19e38df5e9b7", migrations_dir = "drizzle" }
]

[env.stage]
routes = [
    { pattern = "api.stage.shafa.app", custom_domain = true }
]
d1_databases = [
    { binding = "DB", database_name = "stage-shafa-hono-db", database_id = "eb5fb019-ae05-4712-81dc-89f4e152563c", migrations_dir = "drizzle" }
]

[env.production]
routes = [
    { pattern = "api.shafa.app", custom_domain = true }
]
d1_databases = [
    { binding = "DB", database_name = "prod-shafa-hono-db", database_id = "852e5bcb-6da1-47f7-9e50-a60672d5ea90", migrations_dir = "drizzle" }
]
