name = "shafa-hono"
account_id = "287572e2291030d8c5e360fcc593a16b"
compatibility_date = "2024-02-01"
main = "src/index.ts"
node_compat = true
workers_dev = true

[env.production]
routes = [
    { pattern = "api.shafa.app", custom_domain = true }
]