name: Hono Deploy Production

on:
  push:
    branches: main

env:
  NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  cf_deploy_hono_prod:
    name: Deploy Hono to Prod
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://api.shafa.app

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ env.NEON_DATABASE_URL }}
        run: npm run migrate
        working-directory: hono

      - name: Deploy Hono
        uses: cloudflare/wrangler-action@v3
        env:
          DATABASE_URL: ${{ env.NEON_DATABASE_URL }}
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          command: deploy --env production
          workingDirectory: hono
          packageManager: pnpm
          postCommands: echo "${{ env.DATABASE_URL }}" | pnpm wrangler secret put DATABASE_URL --env production
