name: Hono Integration Checks

on:
  pull_request

jobs:
  format_checks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Check Prettier
        run: npm run check-prettier
        working-directory: hono

      - name: Check ESLint
        run: npm run check-eslint
        working-directory: hono


  compilation_checks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Check TS Compilation
        run: npm run check-ts
        working-directory: hono


  test_smoke:
    runs-on: ${{ matrix.os }}
    needs: compilation_checks

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Run Smoke Tests
        run: npm run test:smoke
        working-directory: hono


  test_matrix:
    runs-on: ${{ matrix.os }}
    needs: test_smoke

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]
        test: [functional, integration, system]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Run Tests
        run: npm run test:${{ matrix.test }}
        working-directory: hono