name: Hono Deploy Production

on:
  push:
    branches: main

env:
  NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_NAME }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  cf_deploy_hono_prod:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ env.NEON_DATABASE_URL }}
        run: npm run migrate
        working-directory: hono

      - name: Deploy Hono
        uses: cloudflare/wrangler-action@v3
        env:
          DATABASE_URL: ${{ env.NEON_DATABASE_URL }}
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          command: deploy --env production
          workingDirectory: hono
          secrets: DATABASE_URL