name: Hono Deploy Production

on:
  push:
    branches: main

jobs:
  cf_deploy_hono:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 18 ]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        working-directory: hono

      - name: Deploy Hono
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy src/index.ts --env production
          workingDirectory: hono