name: Hono Teardown

#on:
#  pull_request:
#    types: [closed]

# TODO NEEDS TO BE REMOVED
on:
  pull_request

env:
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
  NEON_API_TOKEN: ${{ secrets.NEON_API_TOKEN }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  GH_ENV_APP_ID: ${{ secrets.GH_ENV_APP_ID }}
  GH_ENV_APP_PRIVATE_KEY: ${{ secrets.GH_ENV_APP_PRIVATE_KEY }}
  DEPLOY_TAG: shafa-hono-stage-${{ github.event.number }}

jobs:
  neon_delete_branch:
    name: Delete Staging Neon Branch
    runs-on: ubuntu-latest

    steps:
      - name: Delete Staging Neon Branch
        uses: neondatabase/delete-branch-action@v3.1.4
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          branch: ${{ env.DEPLOY_TAG }}
          api_key: ${{ env.NEON_API_TOKEN }}

  cf_teardown_hono:
    name: Teardown Staging Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Teardown Hono
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          command: delete --name ${{ env.DEPLOY_TAG }}
          workingDirectory: hono

  gh_delete_deploy_env:
    name: Delete Github Deploy Environment
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
        id: get-token
        with:
          app-id: ${{ env.GH_ENV_APP_ID }}
          private-key: ${{ env.GH_ENV_APP_PRIVATE_KEY }}

      - name: Delete Github Deploy Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: hono-stage-${{ github.event.number }}
